### ISSUE TITLE
Offline Test Execution - import issues

### ISSUE THREAD

**Issue by peter-angelov** [ALM-Rangers/Offline-Test-Execution-Extension#34]
Hello,

Here is in short what I'm trying to do - by some reasons (change of company ownership), the company I work for, was forced to move all the stuff from one account in **AzureDevOps** to another. So, I, as a QA need to migrate test cases from the old account (6 different projects, with more than 300 test cases) to the new one. Both are on one and the same platform - **Microsoft AzureDevOps**.
So I tried the only one available tool for this - **Offline Test Execution** extension. So the export went well, no issues. The problem comes, when I try to import them in the new account - I get validation errors (see attached screenshot), I have no idea how to fix this (am I doing something wrong?). Please advice.

![validation_errors](https://user-images.githubusercontent.com/59952229/72503327-1cc7a900-3844-11ea-8594-04b49896b430.png)

**Comment by jesfer** [comment]
Hi Peter,

Have you looked at the Azure DevOps Migration Tools<https://github.com/nkdAgility/azure-devops-migration-tools>? It can export/import test cases and recreate plans/suites… You wont get the test results to carry over but I dont think you would get that from the Offline Test Execution tool either…

Best
/Jesper

Från: peter-angelov<mailto:notifications@github.com>
Skickat: den 16 januari 2020 08:41
Till: ALM-Rangers/Offline-Test-Execution-Extension<mailto:Offline-Test-Execution-Extension@noreply.github.com>
Kopia: Subscribed<mailto:subscribed@noreply.github.com>
Ämne: [ALM-Rangers/Offline-Test-Execution-Extension] Offline Test Execution - import issues (#34)


Hello,

Here is in short what I'm trying to do - by some reasons (change of company ownership), the company I work for, was forced to move all the stuff from one account in AzureDevOps to another. So, I, as a QA need to migrate test cases from the old account (6 different projects, with more than 300 test cases) to the new one. Both are on one and the same platform - Microsoft AzureDevOps.
So I tried the only one available tool for this - Offline Test Execution extension. So the export went well, no issues. The problem comes, when I try to import them in the new account - I get validation errors (see attached screenshot), I have no idea how to fix this (am I doing something wrong?). Please advice.

[validation_errors]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F59952229%2F72503327-1cc7a900-3844-11ea-8594-04b49896b430.png&data=02%7C01%7C%7C3fb3db2d890d44471db208d79a578b8b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637147573097657519&sdata=u2l0njfvBGqkmpeJto1QQRlCJEw0tU%2B7Ue2VCHgos6s%3D&reserved=0>

**Comment by peter-angelov** [comment]
> Hi Peter, Have you looked at the Azure DevOps Migration Tools<https://github.com/nkdAgility/azure-devops-migration-tools>? It can export/import test cases and recreate plans/suites… You wont get the test results to carry over but I dont think you would get that from the Offline Test Execution tool either… Best /Jesper Från

Hi Jesper,

First of all - thank you for the reply. Honestly, I have never heard before for _Azure DevOps Migration Tools._ So I've checked the information available for it and there are two problems:

1. I'm not sure how to configure it, once it's downloaded and installed (in my case I need AzureDevOps to AzureDevOps account, test plan (and suites) migration only
2. I'm not sure how to use it... I've checked the documentation (there is almost nothing in it), and also checked this [video](https://www.youtube.com/watch?v=ZxDktQae10M), but unfortunately, there is only an information regarding installation - not fully clear (for me, at least), but there are no information on how to use it.

Best Regards
Peter

**Comment by jesfer** [comment]
There is a bit of a learning curve to that tool... But if you can get it to work it should be able to do Azure DevOps to Azure DevOps migration. Using that tool you'd first migrate the Test Cases and then recreate the plans/suites.

I've not developed either of these tools but I've used them and I believe the Azure DevOps Migration Tools is your best choice... Best instructions for getting started are the ones I found here: https://nkdagility.github.io/azure-devops-migration-tools/getting-started.md

/Jesper

**Comment by mattias-skold** [comment]
Hi Peter 
The OTE extension purpose is to let people execute test cases offline in an existing test plan. 
Its not a generic export or data migration tool.  You can NOT use the OTE extension to move test plans between different accounts, 

If your looking to migrate test case data - I aggree with Jespers recomendation. 
If its to technical to use, you could try to export the test cases with the OTE extension, modify the excel file, and try to import the test cases by pasting them into the Test Case grid view. That will let you move your test cases over. You will not get the test plan structure or previous test  results though.
