### ISSUE TITLE
Export function does work with Chrome or Edge Chromium

### ISSUE THREAD

**Issue by ghost** [ALM-Rangers/Offline-Test-Execution-Extension#42]
When clicking on the export button nothing happends.

Looking at the URL Created. The Json object is being created however excel never opens.

Works OK in IE.

**Comment by mattias-skold** [comment]
Im guessing this is for TFS onprem and using Chrome version after R83 ?

In such case - **this is a defect in TFS(Azure DevOps server and is fixed in Azure DevOps Server 2020 
Microsoft support can also provide patches for older tfs versions.** 

**Background:** 
Chrome changes (broke backward compat) for handling of sandboxed iframes with update 83. This is documented at https://www.chromestatus.com/feature/5706745674465280
TFS/AzureDevOps onprem uses sandboxed iframes for extensions, this is a part of your tfs installation and nothing extensions can fix. 
Microsoft has fixed this in Azure DevOps 2020 and if you contact Microsoft Support they whouldbe able to help you patch older versions of tfs.

**Comment by mattias-skold** [comment]
This is also a duplicate with issue #38
