### ISSUE TITLE
Export to excel failed

### ISSUE THREAD

**Issue by ondro21** [ALM-Rangers/Offline-Test-Execution-Extension#44]
After click on button, nothing hapents. In console of chrome is this: Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. See https://www.chromestatus.com/feature/5706745674465280 for more details.

Thanks
Ondro

**Comment by mattias-skold** [comment]
Duplicate with #42 and others 

Copying ...

 Im guessing this is for TFS onprem and using Chrome version after R83 ?

In such case - this is a defect in TFS(Azure DevOps server and is fixed in Azure DevOps Server 2020
Microsoft support can also provide patches for older tfs versions.

Background:
Chrome changes (broke backward compat) for handling of sandboxed iframes with update 83. This is documented at https://www.chromestatus.com/feature/5706745674465280
TFS/AzureDevOps onprem uses sandboxed iframes for extensions, this is a part of your tfs installation and nothing extensions can fix.
Microsoft has fixed this in Azure DevOps 2020 and if you contact Microsoft Support they whould be able to help you patch older versions of tfs.
