### ISSUE TITLE
Download is disallowed in Chrome > v83

### ISSUE THREAD

**Issue by keckxde** [ALM-Rangers/Offline-Test-Execution-Extension#46]
Hi @all,

I am new to the "Offline-Test-Execution-Extension", and tried to use it in our environment.

It seems to be installed correctly, as I can see the additional tab **Offline test execution** inside the Test Plans section,
and also the list of Test Plans, that it extracts from it.

My Problem starts when clicking the **Export to Excel** button. 
With the current Google Chrome or MS Edge, I get the following error message in the JS Console:

`The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. See https://www.chromestatus.com/feature/5706745674465280 for more details`

Example output in the JS debug console - everything seems to be fine but the download:

![image](https://user-images.githubusercontent.com/36791812/109604636-25e90780-7b24-11eb-8a18-c83046c14c19.png)

**Comment by mattias-skold** [comment]
Copying response from #38, #42 & #43

Im guessing this is for TFS/Azure Devops Server (onprem) and using Chrome (or cromium browsers) version after R83 ?

**In such case - this is a defect in TFS(Azure DevOps server and is fixed in Azure DevOps Server 2020
Microsoft support can also provide patches for older tfs versions.**

Background:
Chrome changes (broke backward compat) for handling of sandboxed iframes with update 83. This is documented at https://www.chromestatus.com/feature/5706745674465280
TFS/AzureDevOps onprem uses sandboxed iframes for extensions, this is a part of your tfs installation and nothing extensions can fix.
**Microsoft has fixed this in Azure DevOps 2020 and if you contact Microsoft Support they whouldbe able to help you patch older versions of tfs.**
