### ISSUE TITLE
Azure DevOps Server 2019 can't export to Excel

### ISSUE THREAD

**Issue by dennisl68-castra** [ALM-Rangers/Offline-Test-Execution-Extension#50]
Clicking on Export doesn't create an Excel sheet.
Our server doesn't have access to Internet...

![image](https://user-images.githubusercontent.com/49750419/121235761-7e534200-c895-11eb-9a05-ca649562d0f6.png)

**Comment by mattias-skold** [comment]
Copying response from #38, #42 & #43

Im guessing this is for TFS/Azure Devops Server (onprem) and using Chrome (or cromium browsers) version after R83 ?

In such case - this is a defect in TFS(Azure DevOps server and is fixed in Azure DevOps Server 2020
Microsoft support can also provide patches for older tfs versions.

Background:
Chrome changes (broke backward compat) for handling of sandboxed iframes with update 83. This is documented at https://www.chromestatus.com/feature/5706745674465280 
TFS/AzureDevOps onprem uses sandboxed iframes for extensions, this is a part of your tfs installation and nothing extensions can fix.
Microsoft has fixed this in Azure DevOps 2020 and if you contact Microsoft Support they whouldbe able to help you patch older versions of tfs.

**Comment by dennisl68-castra** [comment]
Thx @mattias-skold, that resolved my issue.
