### ISSUE TITLE
No valid test point to import found

### ISSUE THREAD

**Issue by edwardwwx** [ALM-Rangers/Offline-Test-Execution-Extension#6]
import error :No valid test point to import found,why?

**Comment by mattias-skold** [comment]
The imported data is checked against existing test points, and the test point Id, tester and config is verified to be the same before proceeding.

In short, the test point specified in the xsl cant be found in TFS/VSTS

**Comment by edwardwwx** [comment]
Thanks, plug-in is the need to download a dependency package?

**Comment by edwardwwx** [comment]
Refused to execute script from 'http://tfsdev.taas.com:8080/tfs/_apis/public/gallery/publisher/ats/extension/vso-offlinetestexecution2/0.1/assetbyname/scripts/OfflineTesting.js' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

**Comment by mattias-skold** [comment]
A little bit of contexted would be good, Im guessing that you tried to rebuild and package the extension and upload it to your server ? What version of tfx did you use ?

**Comment by jh8c** [comment]
I am experiencing the same issue as described in this post ("No valid test point to import found"). What I want to do is to export an empty Excel-sheet, type in the data and then import the excel-sheet to VSTS. 

Having read the reply to this issue it seems like this is not possible because the test point that i have added to my excel-sheet (obviously) is not present in VSTS. 

Will this option be possible in the future?

**Comment by mattias-skold** [comment]
To be honest I dont think that is something we will add in the future.
There is many reasons for this. 
- It doesnt fit the purpose of the extension 
- Adding test cases from excel is already supported by Azure Dev Ops out of the box
- The current format doesnt provide enough information for creating test points.
